-- Blog Posts Table for SEO Content
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS blog_posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'News',
    featured BOOLEAN DEFAULT false,
    seo_keywords TEXT[],
    read_time TEXT,
    published BOOLEAN DEFAULT true,
    medium_url TEXT,
    substack_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index for fast slug lookups
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);

-- Index for category filtering
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON blog_posts(category);

-- Index for published posts
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(published) WHERE published = true;

-- Enable RLS
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- Public can read published posts
CREATE POLICY "Public can read published blog posts"
    ON blog_posts FOR SELECT
    USING (published = true);

-- Service role can do everything
CREATE POLICY "Service role full access"
    ON blog_posts FOR ALL
    USING (auth.role() = 'service_role');

-- Grant read access to anonymous users
GRANT SELECT ON blog_posts TO anon;
GRANT SELECT ON blog_posts TO authenticated;

COMMENT ON TABLE blog_posts IS 'SEO blog posts generated by the content agent';
